apiVersion: v1
kind: Secret
metadata:
  name: shoplite-secrets
  namespace: shoplite
type: Opaque
stringData:
  USER_DB_USER: shoplite_user
  USER_DB_PASSWORD: change-me-users
  USER_DB_NAME: shoplite_users
  ORDER_DB_USER: shoplite_order
  ORDER_DB_PASSWORD: change-me-orders
  ORDER_DB_NAME: shoplite_orders
  MONGO_USER: shoplite_catalog
  MONGO_PASSWORD: change-me-catalog
  MONGO_DB_NAME: shoplite_catalog
  REDIS_PASSWORD: change-me-notifications
  RABBITMQ_USER: shoplite
  RABBITMQ_PASSWORD: change-me-rabbitmq
  USER_DATABASE_URL: "postgresql+psycopg://shoplite_user:change-me-users@user-db:5432/shoplite_users"
  ORDER_DATABASE_URL: "postgresql+psycopg://shoplite_order:change-me-orders@order-db:5432/shoplite_orders"
  MONGO_URI: "mongodb://shoplite_catalog:change-me-catalog@catalog-db:27017/shoplite_catalog?authSource=admin"
  REDIS_URL: "redis://:change-me-notifications@notification-db:6379/0"
  RABBITMQ_URL: "amqp://shoplite:change-me-rabbitmq@rabbitmq:5672/"
