apiVersion: v1
kind: ConfigMap
metadata:
  name: shoplite-config
  namespace: shoplite
data:
  LOG_LEVEL: "INFO"
  HTTP_TIMEOUT_SECONDS: "3"
  NOTIFICATION_TTL_SECONDS: "86400"
  MONGO_DB_NAME: "shoplite_catalog"
  USER_SERVICE_URL: "http://user-service:8000"
  CATALOG_SERVICE_URL: "http://catalog-service:8000"
