apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc
  namespace: shoplite
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: shoplite
spec:
  replicas: 1
  selector:
    matchLabels: { app: order-db }
  template:
    metadata:
      labels: { app: order-db }
    spec:
      containers:
        - name: order-db
          image: postgres:16.4-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: shoplite-secrets, key: ORDER_DB_NAME } }
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: shoplite-secrets, key: ORDER_DB_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: shoplite-secrets, key: ORDER_DB_PASSWORD } }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "300m", memory: "256Mi" }
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: order-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: shoplite
spec:
  selector: { app: order-db }
  ports:
    - port: 5432
      targetPort: 5432
